### ISSUE TITLE
Implement the neural algorithm of artistic style

### ISSUE THREAD

**Issue by GlebSBrykin** [mashmawy/AlbiruniML#1]
How about to implement the neural algorithm of the artistic style on the basis of this repository: https://github.com/lizeng614/SqueezeNet-Neural-Style-Pytorch? This implementation is very lightweight(which is important when using CPU) and can be easily ported to AlbiruniML. I already have SqueezeNet1_1 weights in your library format.
[WeightsAndBiases.zip](https://github.com/mashmawy/AlbiruniML/files/2522894/WeightsAndBiases.zip)
In addition, there is a Javascript code for this network for TFJS. 
[models.zip](https://github.com/mashmawy/AlbiruniML/files/2522897/models.zip)

**Comment by GlebSBrykin** [comment]
I must say that I tried to implement the algorithm myself(https://github.com/PABCSoft/NeuralArt), but I made a mistake in the code that I still can't find. In addition, I realized that the algorithm does not need to use a VGG neural network, there are implementations that use a much lighter network - SqueezeNet1.1 and achieve very beautiful results with many times less resource consumption.

**Comment by mashmawy** [comment]
OK i will try but i'am not familiar with pytorch so its going to take a while

**Comment by GlebSBrykin** [comment]
I found another implementation on TensorFlow: https://github.com/zym1119/Style_transfer_tf_cs231n. It will be easier to implement on AlbiruniML because your library is based on TensorFlow.

**Comment by mashmawy** [comment]
very good

**Comment by GlebSBrykin** [comment]
Another option on TensorFlow: https://github.com/peterkim95/style-transferer

**Comment by GlebSBrykin** [comment]
I implemented SqueezeNet1.1 for AlbiruniML.

[SqueezeNet.zip](https://github.com/mashmawy/AlbiruniML/files/2558327/SqueezeNet.zip)

To compile, run Compile.bat.

**Comment by mashmawy** [comment]
awesome, i'll use this

**Comment by GlebSBrykin** [comment]
An unknown internal error occurs during startup.
[SqueezeNet_Styler.zip](https://github.com/mashmawy/AlbiruniML/files/2568379/SqueezeNet_Styler.zip)

**Comment by GlebSBrykin** [comment]
Is there news?

**Comment by mashmawy** [comment]
not yet, just finished my postgraduate midterms

**Comment by mashmawy** [comment]
I implemented the styler but i am facing problems with adam optmizier it's seems there is a bug on it.
i used momentum optmizer it work but not the perfect results.
i will clean the code and upload it soon.

**Comment by GlebSBrykin** [comment]
I also noticed that. Could you please send your code to my email: PABCSoft@yandex.ru? I'd really like to see it.

**Comment by mashmawy** [comment]
here is the code
[SqueezeNetModel.zip](https://github.com/mashmawy/AlbiruniML/files/2613310/SqueezeNetModel.zip)

**Comment by mashmawy** [comment]
i tried to send the code to your email but gmail prevent source code and binary files attachments.

**Comment by GlebSBrykin** [comment]
Thanks, but how do I use the code? An exception is thrown when the image is saved.

**Comment by GlebSBrykin** [comment]
Got it, I replaced the old files AlbiruniML for a new one.

**Comment by GlebSBrykin** [comment]
Strange, I don't see a mistake in Adam...

**Comment by mashmawy** [comment]
i dont think that the problem in adam it self, i think the problem is in Ops or the Backend kernels.
i will implement unit test for adam and try to trace the problem.

**Comment by GlebSBrykin** [comment]
![results1](https://user-images.githubusercontent.com/36363358/49012063-509bc700-f189-11e8-935a-9b5b2de5edf8.png)
![results2](https://user-images.githubusercontent.com/36363358/49012064-509bc700-f189-11e8-9231-4775d310d2eb.png)
![results3](https://user-images.githubusercontent.com/36363358/49012065-509bc700-f189-11e8-860f-39728c1e30ec.png)
![results4](https://user-images.githubusercontent.com/36363358/49012066-509bc700-f189-11e8-83d9-6a097d4ff78c.png)
![results5](https://user-images.githubusercontent.com/36363358/49012067-509bc700-f189-11e8-9a28-7f74020d708e.png)
![results6](https://user-images.githubusercontent.com/36363358/49012068-51345d80-f189-11e8-8426-dcbdb4e13883.png)
![results7](https://user-images.githubusercontent.com/36363358/49012069-51345d80-f189-11e8-9514-89ed9e5c81a4.png)

**Comment by GlebSBrykin** [comment]
Adam optimizer.

**Comment by GlebSBrykin** [comment]
Content Weight = 1e-3.

**Comment by mashmawy** [comment]
perfect

**Comment by GlebSBrykin** [comment]
Peek. I may have made a mistake here, but it's probably the mistake you're looking for.
[SqueezeNetModel.zip](https://github.com/mashmawy/AlbiruniML/files/2615772/SqueezeNetModel.zip)

**Comment by mashmawy** [comment]
i see

**Comment by GlebSBrykin** [comment]
I noticed that the change in TVLoss weight greatly affects the quality of the result. The more weight-the faster the error falls.

**Comment by PABCSoft** [comment]
Any ideas?

**Comment by mashmawy** [comment]
i'am working on it

**Comment by GlebSBrykin** [comment]
Apparently, the error in the reverse distribution is contained in ConvNetCS.
