### ISSUE TITLE
Error in back propagation through pooling layers

### ISSUE THREAD

**Issue by GlebSBrykin** [mashmawy/AlbiruniML#2]
Layer averaging pooling does not pass through the gradient, and a layer max pooling causes exception during reverse circulation.

**Comment by mashmawy** [comment]
can you give the exception type and stack trace.
can you include the library project and reference it and try to regenerate the exception and give me your feedback

**Comment by GlebSBrykin** [comment]
Here's the full code: 
[SqueezeNet_Styler.zip](https://github.com/mashmawy/AlbiruniML/files/2594768/SqueezeNet_Styler.zip)
If you use MaxPool, an exception is thrown(my research has shown that this is due to the fact that back propagation through the layer requires maximum indexes that have not been initialized). If you use AvgPool, that gradient simply does not pass through it. That's why I can't start styling. And did you manage to do it?

**Comment by GlebSBrykin** [comment]
I can give a simpler example with VGG16. There this problem is clearly visible.

**Comment by mashmawy** [comment]
there was a bug in max pool backpropagation, it's now fixed.
